include_directories(
        .
        ${CMAKE_SOURCE_DIR}/src
        ${CMAKE_SOURCE_DIR}/dep/bounce
        ${CMAKE_SOURCE_DIR}/src/rpc
        ${CMAKE_SOURCE_DIR}/src/test
        ${CMAKE_SOURCE_DIR}/src/include
        ${CMAKE_SOURCE_DIR}/src/include/json
)